version: "3"
services:
  cassandra:
    image: cassandra:latest
    restart: always
    container_name: "catssandra"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    ports:
      - "9042:9042"
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra